spring:
  application:
    name: Lesson-Spring
  datasource:
    url: jdbc:h2:mem:test
    username: gor
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update